# Generated by Django 4.0.1 on 2022-01-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='corousel',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
