# Generated by Django 4.0.1 on 2022-02-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0003_employes'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video')),
            ],
        ),
    ]
