# Generated by Django 4.0.1 on 2022-02-01 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0004_videomedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomedia',
            name='video',
            field=models.FileField(upload_to='video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
