# Generated by Django 4.0.1 on 2022-02-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0005_alter_videomedia_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('name', models.CharField(max_length=60)),
                ('desc', models.TextField(max_length=200)),
            ],
        ),
    ]
