# Generated by Django 4.0.1 on 2022-02-03 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0006_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
    ]
