# Generated by Django 4.0.1 on 2022-02-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0007_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='images')),
            ],
        ),
    ]
